### PR TITLE
Initialise

### PR DESCRIPTION
**Pull request by mattgarner**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @mattgarner and @woook)

___
*[nirvana_tx_check.py, line 14 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JxAfM8eUCelozaXRw:-M7JxAfM8eUCelozaXRx:b-sa6lr4) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L14)):*
> ```
> gff_gene_name = None
> ```
local variable 'gff_gene_name' is assigned to but never used
___
*[nirvana_tx_check.py, line 15 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JxV_C0OXCvEkBFdPe:-M7JxV_C0OXCvEkBFdPf:b-3a3fuv) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L15)):*
> ```
> gff_transcript = None
> ```
Repeated on line 26
___
*[nirvana_tx_check.py, line 16 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JxHNA4RfPD4NofYLb:-M7JxHNA4RfPD4NofYLc:b-jieomg) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L16)):*
> ```
> gff_tag = ""
> ```
local variable 'gff_tag' is assigned to but never used
___
*[nirvana_tx_check.py, line 26 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JxgQl-mDahkcnvkf6:-M7JxgQl-mDahkcnvkf7:bw83ueu) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L26)):*
> ```
>  gff_transcript = None
> ```
Repeat of line 15
___
*[nirvana_tx_check.py, line 41 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JyvSc6jOOq4josgvj:-M7JyvSc6jOOq4josgvk:b9w8gwp) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L41)):*
> ```
> transcritps
> ```
transcripts
___
*[nirvana_tx_check.py, line 78 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JycX44rkwfYidP0El:-M7JycX44rkwfYidP0Em:bgxw0i6) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L78)):*
> ```
> def main
> ```
I can't check that the code works as I don't have the GFF files but I'm sure you've tested as you've provided an example of a passing and failing input file, so I'm happy. As you said, it's not a complex script.

And sets vs lists - that's the kind of thing that will never stick in my head :older_man:

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @mattgarner and @woook)

___
*[nirvana_tx_check.py, line 78 at r3](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-M7JycX44rkwfYidP0El:-M7LjTBhEQzXP9xTcjFS:b-dza9j6) ([raw file](https://github.com/eastgenomics/check_nirvana_genes2transcripts/blob/0d596543760afb255abc70b74104ad6747876562/nirvana_tx_check.py#L78)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> def main
> ```
I can't check that the code works as I don't have the GFF files but I'm sure you've tested as you've provided an example of a passing and failing input file, so I'm happy. As you said, it's not a complex script.

And sets vs lists - that's the kind of thing that will never stick in my head :older_man: 
</blockquote></details>

If you really want the gff it's contained within https://illumina-annotation.s3.amazonaws.com/Cache/v26.tar.gz
but yes, I have tested it and shown it to correctly pass and fail transcripts

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by woook — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1#-:-M7M_OMv0hND7Ndr94Dw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by woook — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/check_nirvana_genes2transcripts/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
